

1. What are the details of all cars purchased in the year 2022?
select sls.salesman_id,
       sls.name,
       sls.age,
       sls.city,
       c.car_id,
       c.make,
       c.type,
       c.style,
       c.cost_$,
       s.purchase_date
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
where extract(year from s.purchase_date) = 2022;


2. What is the total number of cars sold by each salesperson?
select sls.name,
       count(c.car_id) as Total_Cars
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
group by sls.name 
order by count(c.car_id) desc;


3. What is the total revenue generated by each salesperson?
select sls.name,
       sum(c.cost_$) as Total_Renevue
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
group by sls.name
order by sum(c.cost_$) desc;



4. What are the details of the cars sold by each salesperson?
select distinct sls.name,
	   c.make,
       c.type,
       c.style,
       c.cost_$,
       s.purchase_date
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
;


5. What is the total revenue generated by each car type?
select type as car_type,
       sum(cost_$) as Total_Revenue
from cars
group by type
order by sum(cost_$) desc;

6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select  c.make,
        c.type,
        c.style,
        c.cost_$,
        s.purchase_date
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
where extract(year from s.purchase_date) = 2021 and sls.name = 'Emily Wong';


7. What is the total revenue generated by the sales of hatchback cars?
select style,
       sum(cost_$) as Total_Revenue
from cars
where style = 'Hatchback';


8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select c.style,
       sum(c.cost_$) as Total_Revenue
from cars as c
join sales as s 
on c.car_id=s.car_id
where c.style = 'SUV' and extract(year from s.purchase_date) = 2022;

9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select sls.name,
       sls.city,
       count(s.sale_id) as Highest_Unit_sold
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
where extract(year from s.purchase_date) = 2023
group by sls.name,sls.city
order by count(s.sale_id) desc
limit 1
;


10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select sls.name,
       sls.age,
       sum(c.cost_$) as Highest_Revenue
from cars as c
join sales as s 
on c.car_id=s.car_id
join salespersons as sls
on s.salesman_id=sls.salesman_id
where extract(year from s.purchase_date) = 2022
group by sls.name,sls.age
order by sum(cost_$) desc
limit 1
;



